### ISSUE TITLE
I have a question about the code

### ISSUE THREAD

**Issue by JCristobal** [end3r/FrontInvaders#1]
Hello, I´m working with html5 and I want to add to your game buttons that perform the same function in shooting and movement.
But i don´t know how can fix the variable of movement from the code... 

This code:  `this.pressed.shoot = true;` in input.js does nothing.

any help?  :weary:

**Comment by end3r** [comment]
You have to add another `case` to the `switch(e.keyCode)` with your specific `keyCode` you want to use.

**Comment by JCristobal** [comment]
I do not want to change the state with a key, I want to do with a button on the same page (`<button type="button" name="button_shoot" value="shoot"  id="shoot_button" onClick="GAME.dispara()">Shoot</button>` with html5 ): so I can not use keyboard events.

![new buttons](http://i.imgur.com/k8YZImr.png)

In input.js i make the function

```
GAME.dispara = function(){
    GAME.$id('shoot_button').onclick = function() {
        this.pressed.shoot = true;                        // what function should call here?
    };

};
```

**Comment by end3r** [comment]
You can execute the contents of the shoot action in the `frame` function, so it would be something like this:

```
GAME.$id('shoot_button').onclick = function() {
    console.log("dispara");
    if(GAME.BULLETS.length < GAME.Config.bulletLimit) {
        GAME.BULLETS[GAME.BULLETS.length] = GAME.Utils.ActivateBullet();
    }
};
```

In that case you don't have to add anything in the `onClick` of the button:

`<button type="button" name="button_shoot" value="shoot" id="shoot_button">Shoot</button>`

It could be even a paragraph, for example `<p id="shoot_button">Shoot</p>` - all you need is the proper ID.

You can do the similar thing with the left/right buttons.

**Comment by JCristobal** [comment]
it´s work! Thaks very much, I'm beginning and I did not understand some functions.

Congratulations for the game!
